spring:
  application:
    name: ITEMS-SERVICE
  config:
    import: "optional:configserver:"
  datasource:
    url: "jdbc:mysql://localhost:3306/copa"
    username: root
    password: chowd@ry1
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  

server:
  port: 8001
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
  
  